//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub mod prelude;

pub mod downvote;
pub mod entry;
pub mod favorite;
pub mod silenced_user;
pub mod title;
pub mod token;
pub mod upvote;
pub mod user;
